# Generated by Django 4.1.2 on 2023-06-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso',
            field=models.TextField(null=True),
        ),
    ]
