# Generated by Django 4.1.2 on 2023-06-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice1', '0002_country_iso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('field_of_business', models.CharField(max_length=255)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('company_representative', models.CharField(max_length=255)),
                ('company_tax_id', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('date_of_agreement', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Satis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secenek1', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
