# Generated by Django 4.1.2 on 2023-06-24 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice1', '0003_company_satis'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='satis',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='invoice1.satis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='satis',
            name='secenek1',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
