# Generated by Django 4.1.2 on 2023-06-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice1', '0005_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='eskiinvoice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='guncelleme',
            field=models.BooleanField(default=False),
        ),
    ]
